name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make build dir
      run: mkdir -p build
    - name: cmake Config
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: make result dir
      working-directory: ${{github.workspace}}
      run: mkdir -p test/test-results
    - name: run tests
      working-directory: ${{github.workspace}}/build
      run: ./llibUnitTests* --gtest_output=xml:../test/test-results/llibTests.xml
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: testReport
        path: -{{github.workspace}}/test/test-results/llibTests.xml
  
