name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildAndTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: makebuilddir
      run: mkdir -p build
    - name: cmakeConfig
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: makeresultdir
      working-directory: ${{github.workspace}}
      run: mkdir -p test/test-results
    - name: runtests
      working-directory: ${{github.workspace}}/build
      run: ./llibUnitTests* --gtest_output=xml:../test/test-results/llibTests.xml
    
  
